#!/usr/bin/env sh

CMD="xrandr"

for OUTPUT in $(xrandr | awk '/ connected/{print $1}'); do
    RES=$(xrandr --current | grep -A1 "^$OUTPUT" | tail -n1 | awk '{print $1}')
    
    CURRENT_HZ=$(xrandr --current | grep -A1 "^$OUTPUT" | tail -n1 | sed 's/.* \([^*]*\)\*.*/\1/' | sed 's/\..*//')
    
    MAX_HZ=$(xrandr | grep -A20 "^$OUTPUT" | grep "$RES" -A5 | grep -o '[0-9]\+\.[0-9]\+' | sort -nr | head -n1 | cut -d. -f1)
    MIN_HZ=$(xrandr | grep -A20 "^$OUTPUT" | grep "$RES" -A5 | grep -o '[0-9]\+\.[0-9]\+' | sort -n | head -n1 | cut -d. -f1)
    
    if [ "$CURRENT_HZ" = "$MAX_HZ" ]; then
        CMD="$CMD --output $OUTPUT --mode $RES --rate $MIN_HZ"
    else
        CMD="$CMD --output $OUTPUT --mode $RES --rate $MAX_HZ"
    fi
done

eval $CMD
