#!/usr/bin/env sh
rm -f ~/.bspwmrc.log
exec &>> ~/.bspwmrc.log
set -x


pkill picom
picom --config $HOME/.config/picom/picom.conf &


output=$(xrandr | grep " connected" | cut -d' ' -f1)
mode=$(xrandr | grep "^$output " -A5 | grep '*' | awk '{print $1}')
xrandr --output "$output" --mode "$mode" --rate 144

pkill sxhkd
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

xinput set-prop "ASUF1204:00 2808:0202 Touchpad" "libinput Natural Scrolling Enabled" 1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	3
bspc config window_gap          	12

	bspc config top_padding			50
	bspc config bottom_padding			0

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

lxqt-policykit-agent &




pkill feh
feh --bg-fill /home/jeronimo/.dotfiles/modulos/bspwm/wallpaper.png &

xset s off
xset s noblank
xset -dpms

bspc rule -a Polybar layer=below
# Restart Polybar
pkill polybar

polybar left &
polybar center &
polybar right &

pkill nm-applet
nm-applet &


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

