
set -g set-clipboard on

unbind h
unbind j
unbind k
unbind l

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

